### ISSUE TITLE
Error on display of image gallery

### ISSUE THREAD

**Issue by BalachandraTejas** [nstaeger/WordPress-UIkit-Starter-Theme#2]
There was an error on display of gallery of images, showing $attributes variable is not an array.
I made some changes in my fork, 
https://github.com/BalachandraTejas/WordPress-UIkit-Starter-Theme/blob/master/php/UIkitGallery.php

Please check them and if possible suggest the right way.
Thank you

**Comment by nstaeger** [comment]
Thanks for reporting. In the end it was a spelling mistake https://github.com/nstaeger/WordPress-UIkit-Starter-Theme/commit/2216f0e81e74e3723686abb871b8a0eb9f053fd5#diff-2ee6ddef85a7614e98637b6a441615f2R16
